### ISSUE TITLE
Awk error message whenever changing directories using fish.

### ISSUE THREAD

**Issue by g5becks** [b4b4r07/enhancd#132]
**What did you expect to happen?**
Functionality described on the readme.md

**What actually happened?**
Normal cd command is used and error is raised.

**Output**
`awk: cannot open /home/beckspoppn/.config/fisher/github.com/b4b4r07/enhancd/lib/step_by_step.awk (No such file or directory)
`

**Comment by grzkv** [comment]
Same here.

**Comment by RaphaelNanje** [comment]
Again here.

OS: Manjaro Linux x86_64 
Fish: 3.1.2

**Comment by MagnusKoudahl** [comment]
I tracked this to a bug with using fisher.
enhancd.fish sets ENHANCD_ROOT to a subdir of .config while fisher puts the scripts under .cache

The quick fix is to change the line
`if ! set -q ENHANCD_ROOT; set -gx ENHANCD_ROOT "$HOME/.config/fisher/github.com/b4b4r07/$name"; end`
to
`if ! set -q ENHANCD_ROOT; set -gx ENHANCD_ROOT "$HOME/.cache/fisher/github.com/b4b4r07/$name"; end`
in enhancd.fish.

Fixed it on my end. If it works for you as well, I'll make a PR

**Comment by crumley** [comment]
Works for me!

**Comment by evilhamsterman** [comment]
It looks like the cause is this PR https://github.com/jorgebucaran/fisher/pull/571 if you are using fisher

**Comment by evilhamsterman** [comment]
Based on that PR the better location is `$HOME/.local/share/fisher/github.com/b4b4r07/enhancd` because the .cache dir is just a cache and could be wiped. `.local/share` is the actual data location

**Comment by zoomido** [comment]
I'm also getting this: `gawk: fatal: can't open source file `/lib/step_by_step.awk' for reading (No such file or directory)`
but your fix didn't work since my HOME/.cache doesn't have a fisher folder. I actually can't seem to find the enhancd lib folder anywhere within `.config`. To me it looks like a lot of depencies aren't installed.

**Comment by ibeex** [comment]
https://github.com/jorgebucaran/fisher/issues/625 manually creating fixes it

**Comment by jorgebucaran** [comment]
Fixed in https://github.com/b4b4r07/enhancd/commit/7085570557da3bbed219d103cf53102babba4243. Please update to the latest `enhancd` and let us know if you still have any issues. 👋 

@ibeex @zoomido @evilhamsterman @crumley @g5becks @MagnusKoudahl

**Comment by g5becks** [comment]
@jorgebucaran Unfortunately, I am still getting the same error after installing today on a fresh arch linux box.

**Comment by jorgebucaran** [comment]
@g5becks Using the latest Fisher to install b4b4r07/enhancd?

**Comment by g5becks** [comment]
@jorgebucaran 

I think so, I just install fisher a couple of days ago.
```
fisher -v
fisher, version 4.1.0
```

**Comment by jorgebucaran** [comment]
@g5becks Thanks for the info! We're currently tracking this in https://github.com/b4b4r07/enhancd/pull/141. The PR fixes some errors, but it's still incomplete. Please subscribe there for updates. 🙏

**Comment by b4nst** [comment]
For me it was in `~/.config/fish/fish_variables` that `ENHANCD_ROOT` was set to an incorrect path (`/functions/enhancd`) fixing it fixed the issue

**Comment by d3dave** [comment]
@g5becks @b4nst Fixed in https://github.com/b4b4r07/enhancd/pull/143

**Comment by VietTralala** [comment]
Still occurs on raspbian 
```
$ fisher --version
fisher, version 4.3.1

$ fish --version
fish, version 3.1.2
```

enhancd was installed via fisher ```fisher install b4b4r07/enhancd```
The file `~/.config/fish/fish_variables` contains the line `SETUVAR --export ENHANCD_ROOT:/home/pi/\x2econfig/fish/functions/enhancd`
